root: true

extends:
  - '@comicrelief/eslint-config/mixins/base'
  - '@comicrelief/eslint-config/mixins/ts'
  - '@comicrelief/eslint-config/mixins/jsdoc'

rules:
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-explicit-any': off
